service: react-cognito-starter 

package:
  exclude:
    - client/**

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10


functions:
  hello:
    handler: handler.hello

resources:
  - ${file(./resources/cognito-user-pool.yml)}
  - ${file(./resources/cognito-identity-pool.yml)}